# Generated by Django 4.0.2 on 2022-08-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='codigo',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
