# Generated by Django 4.0.2 on 2022-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_departamentos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='departamento',
            field=models.CharField(max_length=40),
        ),
    ]
