# Generated by Django 4.0.2 on 2022-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_departamentos_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
